name: super_repository
description: A new Flutter project.
version: 0.0.7

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity_plus: ^2.2.0
  internet_connection_checker: ^0.0.1+3

  dio: ^4.0.4
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true